name: "Release"

on:
  workflow_dispatch:

jobs:
  release-xyce:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    container: ghcr.io/siliconplatformslab/xyce:master
    steps:
      - uses: actions/checkout@v5
      - uses: wusatosi/setup-gh@v1

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          name: Xyce ${{ steps.date.outputs.date }}
          draft: true
          prerelease: false

      - name: Upload assets
        run: |
          cd /dist;
          ls -lah;
          for artefact in XyceOpenSource*; do
            echo $artefact;
            echo release-${{ steps.date.outputs.date }};
            gh release upload release-${{ steps.date.outputs.date }} $artefact;
          done;
